stages:
    - build
    - deploy

build-job:
    stage: build
    image: docker:24.0-dind
    variables:
        DOCKER_IMAGE: buildings_image
    services:
        - docker:24.0-dind
    before_script:
        - echo "$CI_REGISTRY_USER"
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - |
            if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
              docker build  -t "$DOCKER_IMAGE" -f Dockerfile.production .
            fi
    only:
        refs:
            - main

deploy-job:
    stage: deploy
    image: alpine:latest
    script:
        - apk add docker
        - docker version
        - wget https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz
        - tar xf doctl-1.64.0-linux-amd64.tar.gz
        - mv doctl /usr/local/bin
        - |
            if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
              doctl auth init -t "dop_v1_b452861bec9814a286f62064bb3a6f95cce2ef0c1fc00e4f657b17b0ba957715"
              echo "Successfull auth!"
              doctl registry login		    
              echo "Successfully logged in!"
              #docker tag buildings_image registry.digitalocean.com/buildings/buildings_image_first
              #docker push registry.digitalocean.com/buildings/buildings_image_first    
              echo "Deploy to production envirement success!"
            fi
    only:
        - main
